# Override file used for configuration wanted on dev but not on prod
version: '3.3'

services: 
    nginx:
        build: 
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes: 
            - ./app:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes: 
            - ./app:/var/www/html
            - "~/.cache/composer:/home/www-data/.composer/cache"