version: '3.3'

networks: 
    default: {}
    dockertoolkit_proxy:
        external: true
    dockertoolkit_db:
        external: true

volumes:
    db: {}

services: 
    db:
        image: mariadb:10.4
        networks: 
            - default
            - dockertoolkit_db
        volumes: 
            - db:/var/lib/mysql
            - ./.docker/mariadb/db-dumps:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=symfony
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=symfony

    nginx:
        working_dir: "/var/www/html"
        networks: 
            - default
            - dockertoolkit_proxy
        depends_on: 
            - php
        labels:
            - traefik.enable=true
            - traefik.port=80
            - traefik.frontend.rule=Host:symfony.local
            - traefik.docker.network=dockertoolkit_proxy
            - ghosts.host=symfony.local
            - ghosts.category=~project
            - ghosts.description=Symfony application.

    php:
        networks: 
            - default
        depends_on: 
            - db
        environment: 
            - UID=${uid}
            - GID=${gid}