version: '3.3'

networks: 
    default: {}

volumes:
    db: {}

services: 
    db:
        image: mariadb:10.4
        networks: 
            - default
        volumes: 
            - db:/var/lib/mysql
            - ./.docker/mariadb/db-dumps:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test

    nginx:
        image: nginx:1.17-alpine
        working_dir: "/var/www/html"
        networks: 
            - default
        ports: 
            - "8080:80"
        volumes: 
            - .:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php

    php:
        build: .docker/php
        working_dir: "/var/www/html"
        networks: 
            - default
        volumes: 
            - .:/var/www/html
            - "~/.cache/composer:/home/www-data/.composer/cache"
        depends_on: 
            - db